replicaCount: 2

image:
  repository: 448049807140.dkr.ecr.us-east-1.amazonaws.com/lily-designer-studio
  tag: "b74772e182f936ceffa549420d4353d9ac64b702"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

database:
  enabled: true
  image: postgres:13
  database: "lily_studio"
  username: "lily_user"
  password: "lily123"
  storage: "5Gi"
  storageClass: "gp2" 
  service:
    port: 5432
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

app:
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

env:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "lily-designer-studio-database"
  DB_PORT: "5432"
  DB_NAME: "lily_studio"
  DB_USER: "lily_user"
  DB_PASSWORD: "lily123"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80